version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propdisp_wordpress
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=dbo740303479
      - WORDPRESS_DB_PASSWORD=eaGsPUuWiQexlyWUkaYC
      - WORDPRESS_DB_NAME=db740303479
      - WORDPRESS_TABLE_PREFIX=WOViPwUh_
    volumes:
      - ./propdisp_wp/wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - propdisp_network

  db:
    image: mysql:5.7
    container_name: propdisp_mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=db740303479
      - MYSQL_USER=dbo740303479
      - MYSQL_PASSWORD=eaGsPUuWiQexlyWUkaYC
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./db740303479_200311.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - propdisp_network

networks:
  propdisp_network:
    driver: bridge

volumes:
  db_data:
